### ISSUE TITLE
Handle seeking in to the middle of a UTF-8 character

### ISSUE THREAD

**Issue by samwho** [samwho/hmm#20]
See this issue for some background: https://github.com/mjc-gh/rev_lines/issues/3.

At the moment it's possible for our line seeking code to find itself returning with the file cursor sat in the middle of a multibyte character that just happens to contain `0x0a` as one of the bytes. Unlikely in English I think, but I've no idea about other languages.

**Comment by Samoxive** [comment]
Thanks to backwards compability of UTF-8 with ASCII encoding, values between 0 and 127 map directly to ASCII equilavents, including `\n`. For a multibyte code point, all bytes have most significant bit set to zero, a cursor searching `0x0a` cannot possibly stop in the middle of a multibyte code point.

**Comment by samwho** [comment]
Awesome! Thanks for clearing that up, Samo. :)
