### ISSUE TITLE
`hmmp` crashes :(

### ISSUE THREAD

**Issue by flonle** [samwho/hmm#27]
Just installed via AUR, but `hmmp` does not work. It instantly crashes (and asks me nicely to submit a report, so here I am).

```
name = 'hmmcli'
operating_system = 'unix:Unknown'
crate_version = '0.5.2'
explanation = '''
Panic occurred in file 'src/entry.rs' at line 91
'''
cause = 'called `Option::unwrap()` on a `None` value'
method = 'Panic'
backtrace = '''

   0: 0x55c8c4c20513 - <unresolved>
   1: 0x55c8c4c31a49 - <unresolved>
   2: 0x7f9924008850 - <unresolved>
   3: 0x7f992400890a - __libc_start_main
   4: 0x55c8c4c2009e - <unresolved>
   5:        0x0 - <unresolved>'''
```

**Comment by samwho** [comment]
Hey! Thanks for taking the time to send this report. Sorry it took me a couple days to see it.

Do you by any chance have no entries? 🙂

**Comment by flonle** [comment]
My apologies, it was human error :sweat_smile: 
The wrong file ended up piped into `hmm`.
The error occurs specifically when the piped file contains only newline characters. When the file is empty or a malformed, `hmmp` exits gracefully.  So maybe still worth dealing with but the error was mine.

**Comment by samwho** [comment]
Regardless what you do as a user, you should never be presented with the error message you saw. I will get a fix out in the next week or two when I can clear an evening to dig in. Thanks so much for the sleuthing, and it's exciting to hear you're making use of the tool.

**Comment by samwho** [comment]
v0.6.0 _should_, in theory, fix the problem you ran in to here. :)
